class Global {
  const Global._();
  static const Global instance = Global._();
  final String warning = 'global.warning';
  final String error = 'global.error';
  final String info = 'global.info';
  final String success = 'global.success';
  final String exit = 'global.exit';
  final String stay = 'global.stay';
  final String search = 'global.search';
  final String all = 'global.all';
  final String food = 'global.food';
  final String drink = 'global.drink';
  final String home = 'global.home';
  final String upload = 'global.upload';
  final String notification = 'global.notification';
  final String profile = 'global.profile';
  final String category = 'global.category';
  final String cancel = 'global.cancel';
  final String next = 'global.next';
  final String ingredients = 'global.ingredients';
  final String steps = 'global.steps';
  final String back = 'global.back';
  final String mins = 'global.mins';
  final String likes = 'global.likes';
  final String settings = 'global.settings';
  final String submit = 'global.submit';
  final String tryAgain = 'global.try_again';
  final String takeFromGallery = 'global.take_from_gallery';
  final String takeFromCamera = 'global.take_from_camera';
  final String deleteRecipe = 'global.delete_recipe';
  final String deleteRecipeConfirmation = 'global.delete_recipe_confirmation';
  final String edit = 'global.edit';
  final String remove = 'global.remove';
  final String restoreImage = 'global.restore_image';
  final String undo = 'global.undo';
}
