// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC90lHXIYWdiQw0fUD9xR17aFfcyaR-ow',
    appId: '1:236382856234:web:3499f7bfcc29970bc28f53',
    messagingSenderId: '236382856234',
    projectId: 'chefio-f46be',
    authDomain: 'chefio-f46be.firebaseapp.com',
    storageBucket: 'chefio-f46be.firebasestorage.app',
    measurementId: 'G-QQE7Q3CKBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ILIkmljKtwF03l_uDfQgDYckk22xcRg',
    appId: '1:236382856234:android:ef4a15af85569320c28f53',
    messagingSenderId: '236382856234',
    projectId: 'chefio-f46be',
    storageBucket: 'chefio-f46be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuhggKrWQSdDZ5lJCR5Vjon_Dyw8LVOzE',
    appId: '1:236382856234:ios:3e4bffffc708f7fec28f53',
    messagingSenderId: '236382856234',
    projectId: 'chefio-f46be',
    storageBucket: 'chefio-f46be.firebasestorage.app',
    iosBundleId: 'com.example.chefioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuhggKrWQSdDZ5lJCR5Vjon_Dyw8LVOzE',
    appId: '1:236382856234:ios:3e4bffffc708f7fec28f53',
    messagingSenderId: '236382856234',
    projectId: 'chefio-f46be',
    storageBucket: 'chefio-f46be.firebasestorage.app',
    iosBundleId: 'com.example.chefioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC90lHXIYWdiQw0fUD9xR17aFfcyaR-ow',
    appId: '1:236382856234:web:56ed12a31aed9cc4c28f53',
    messagingSenderId: '236382856234',
    projectId: 'chefio-f46be',
    authDomain: 'chefio-f46be.firebaseapp.com',
    storageBucket: 'chefio-f46be.firebasestorage.app',
    measurementId: 'G-8ZGX7JS78M',
  );
}
